print("printing Triange")
print("    /|")
print("   / |")
print("  /  |")
print(" /   |")
print("/____|")

print("printing plus")
print("  |")
print("  |")
print("-----")
print("  |")
print("  |")
